---
db:
  conn_string: "host=localhost port=15432 user=companies_db dbname=companies_db sslmode=disable"
  migration_dir: "./sql-migrations"
  migration_table: "migrations"
  max_open_conns: 100
  conn_max_lifetime: 30s
web_api:
  listen: ":8088"
