---
db:
  #conn_string: "host=companies_db port=5432 user=companies_db dbname=companies_db sslmode=disable"
  conn_string: "host=localhost port=15432 user=companies_db dbname=companies_db sslmode=disable" # use this connection for the local run
  migration_dir: "./sql-migrations"
  migration_table: "migrations"
  max_open_conns: 100
  conn_max_lifetime: 30s
web_api:
  listen: ":8088"
geoip:
  allowed_country_name: Cyprus
  endpoint: https://ipapi.co
  timeout: 10s
client_token:
  ttl: 1h
  issuer: testapp
  secret: r4nd0m
