version: "3.9"
services:
  api:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - "companies_db"
    networks:
      - default
    environment:
      - OTEL_SERVICE_NAME=companies
      # Found these variables here https://pkg.go.dev/go.opentelemetry.io/otel/exporters/jaeger#section-readme
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger-agent
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-tracing:14268/api/traces
  companies_db:
    image: "postgres:14.5"
    ports:
      - "15432:5432"
    networks:
      - default
    hostname: companies_db
    environment:
      - POSTGRES_USER=companies_db
      - POSTGRES_DB=companies_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - /Users/zabolotniy/develop/mount/companies_db:/var/lib/postgresql/data
  tracing:
    image: "jaegertracing/all-in-one:1.33"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - default
    hostname: jaeger-tracing